### ISSUE TITLE
"npx create-react-app"  dons't work , why?????

### ISSUE THREAD

**Issue by ahmedelamine** [reactjs/reactjs.org#3139]
that is the Err:
Error: EPERM: operation not permitted, mkdir 'C:\Users\ahmed'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-message.js:38:39) 
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:201:13)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:171:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:321:20)
    at process._fatalException (internal/process/execution.js:164:25)
Install for [ 'create-react-app@latest' ] failed with code 7

**Comment by sijusamson** [comment]
@ahmedelamine this issue is related to permission level, grant permission to the particular directory. This issue is not related to react.

**Comment by ahmedelamine** [comment]
I solved this issue
npm install create-react-app -g
npx create-react-app myapp

**Comment by threepointone** [comment]
This does seem like a permissions issue. This issue also probably belongs in https://github.com/facebook/create-react-app/issues.
