### ISSUE TITLE
The horrible situation of current translation effort

### ISSUE THREAD

**Issue by sJJdGG** [reactjs/reactjs.org#3833]
main translation repo is dead.

you can say it by looking at the long list of not handled [PRs in the repo](https://github.com/reactjs/reactjs.org-translation/pulls)

Translation bot is dead. it doesn't push new commits or does not open new PRs. (I think it's due to renaming primary branch name from "master" to "main" in this repo but I'm not sure)

With current efforts for new docs #3308 and the emphasis on translations, it's an issue that at least should be discussed.

I'm the current maintainer of Persian translation effort and volunteering for any task to fix this situation in the upstream.

**Comment by gaearon** [comment]
Hi, thanks for raising this! We know there’s a backlog of issues but we haven’t prioritised them because the old docs are mostly going to be replaced anyway, so all the focus is on getting them into shape that’s ready for a public beta and to start the next wave of translation effort. We expect that to happen in the next couple of months. As soon as we have a branch up and ready, we’ll need to work with the translation maintainers to figure out a strategy forward. But I wouldn’t suggest putting extra energy into translating the current content. 

> it doesn't push new commits or does not open new PRs. (I think it's due to renaming primary branch name from "master" to "main" in this repo but I'm not sure)

This sounds plausible. We should at least look into this and fix this.

**Comment by gaearon** [comment]
Fix for the bot: https://github.com/reactjs/reactjs.org-translation/pull/170

I'm not sure how to verify the change so I'll ping @tesseralis who helped set it up!

We'll need the translation repos to do the branch rename too.

**Comment by sJJdGG** [comment]
Hi @gaearon
Thanks for fix. I think we should wait until next Monday to verify it. This is the [scheduled time for translation bot](https://github.com/reactjs/reactjs.org-translation/blob/f19b73ae293bf994f15672d9b03ead632e415e9d/Procfile#L1).

And about not putting more effort into the current docs, it's something I really love to do, some other people have put time into translation and opened PRs for it. Not handling them doesn't send the message I like.

I'm already excited for the new docs. From #3308 I understand it's gonna be more interactive and more like a game. I hope I18n is a first class citizen from the start.

**Comment by sJJdGG** [comment]
**Update:** The bot still doesn't work, Things have gone worse actually, Updates don't get deployed anymore (also PR deployment previews) and the main site is stale.
@gaearon @rachelnabors @bvaughn

**Comment by rachelnabors** [comment]
Hello hello! Following up here, @sJJdGG. We're in a bit of a fix—one of those the person who set this up moved on and the supporting system changed type things. We should know more in a week or two. But in the mean time, to move things along, if you could give @bvaughn a specific PR that's failing, we can continue our sleuthwork

**Comment by sJJdGG** [comment]
@bvaughn @rachelnabors Hi! You can check it by browsing the [tutorial page on Persian site](https://fa.reactjs.org/tutorial/tutorial.html) and seeing it's not translated although it's been translated and already merged on [main branch](https://github.com/reactjs/fa.reactjs.org/blob/main/content/tutorial/tutorial.md).

But Vercel check has already been passed on the main branch which should mean the last last changes have already been deployed!

This malfunctioning behavior started after the merge of reactjs/reactjs.org-translation#170. I've merged the tutorial page translation just after that. Main site deployments were good before that. So in addition to not having the Bot working, the deployments don't work either.

PR's preview deployments are working right now though. There used to some permission errors with Vercel bot but not anymore.

**Comment by bvaughn** [comment]
Ah. I think there's some confusion.

The most recent commit (from 2 days ago) was [successfully built by Vercel](https://vercel.com/fbopensource/fa.reactjs.org/AY7mn6LiYKWCqMVesjGRvqGPx9T7) and [deployed here](https://fareactjsorg-git-main-fbopensource.vercel.app/tutorial/tutorial.html) where you can see the tutorial page is translated properly.

However the docs site at fa.reactjs.org is still hosted on Gatsby (not Vercel yet). So it seems like something is wrong with the Gatsby configuration.

**Comment by bvaughn** [comment]
Looks like for some reason, the Netlify settings for fa.reactjs.org still pointed to the `master` branch. Let me change that and see if it fixes things.

**Comment by bvaughn** [comment]
It's fixed!
https://fa.reactjs.org/tutorial/tutorial.html

I just went through the 40ish other configurations and updated them too. Hopefully this will all get better soon. Sorry for the trouble!

**Comment by sJJdGG** [comment]
Thanks @bvaughn!

Shouldn't we keep the issue open until the synchronizer bot gets fixed?

**Comment by bvaughn** [comment]
Sorry. I didn't realize it was still broken.

Your most recent comment about the bot said:
> Update: The bot still doesn't work, Things have gone worse actually, Updates don't get deployed anymore (also PR deployment previews) and the main site is stale.

But updates should now be getting deployed successfully.

What's not working?

**Comment by sJJdGG** [comment]
The synchronizer bot

It's responsible for pushing new commits from reactjs.org repo to all translation repos.

Right now it's not working and all translation repos are stale and behind this repo.

**Comment by bvaughn** [comment]
I see.

I don't see a reason why that would be the case, looking through the bot's code, but I don't have any context on how or where this bot runs or how to configure it. The project's README doesn't have instructions for how to run or test it. 😅

**Comment by bvaughn** [comment]
I tried running the script locally to see if that revealed anything:
```sh
node scripts/sync.js config.json langs/fa.json
```

It seems to checkout the repo correctly, run a pull script and merge changes, but then it fails when it tries to push the changes:
> UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /Users/bvaughn/Documents/git/reactjs.org-translation/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createPullRequest (/Users/bvaughn/Documents/git/reactjs.org-translation/scripts/sync.js:162:7)

That being said, it looks like the bot checks out the translation repos within a local "repo" folder. I wonder if the checkouts just need to be wiped out and recreated or something (after the branch change)?

**Comment by bvaughn** [comment]
Digging in further, I wonder if the `master` -> `main` branch rename was just a coincidence? I see this error after adding an auth token and re-running the sync script:
> remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
> remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
> fatal: unable to access 'https://github.com/reactjs/es.reactjs.org.git/': The requested URL returned error: 403

**Comment by sJJdGG** [comment]
@bvaughn I'm more clueless than you since I don't have access to anything except our own repo. I just know that the last sync PR was opened on Jul 5 (reactjs/fa.reactjs.org/pull/226) and so some change must have happened after that and the only suspect was renaming of the main branch in the upstream repo.

**Comment by bvaughn** [comment]
Fair enough.

I'm going to go ahead and run the sync locally (with my user) to create PRs as a one time temporarily solution to buy some time.

**Comment by bvaughn** [comment]
Also the translations status page is back up now and being served from a new URL:
https://translations.reactjs.org/

**Comment by sJJdGG** [comment]
@bvaughn Thank you for the PRs. Let me know if I can be any help

**Comment by bvaughn** [comment]
I've setup a new script and bot for this. Sync PRs were pushed for all translation forks this morning and will run weekly from now on. I'm going to close this issue for now, since (I think) things are taken care of. Let us know if new problems pop up please.

**Comment by gaearon** [comment]
Issue for new doc translations: https://github.com/reactjs/reactjs.org/issues/4135
