### ISSUE TITLE
create-react-app, Node 17.0.1 -> digital envelope routines::unsupported

### ISSUE THREAD

**Issue by waugh** [reactjs/reactjs.org#4073]
Follow the advice about using create-react-app on page  https://reactjs.org/docs/create-a-new-react-app.html , using Node 17.0.1. Step `npm start` results in:

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (node_modules/webpack/lib/NormalModule.js:471:10)
    at node_modules/webpack/lib/NormalModule.js:503:5
    at node_modules/webpack/lib/NormalModule.js:358:12
    at node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (node_modules/loader-runner/lib/LoaderRunner.js:221:10)
node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^
```

At the time of this writing, I have not yet tried it with an older Node. But the advice on the page says "Node >= 14.0.0 and npm >= 5.6", and both those constraints are satisfied, and I should think you would not want to publish advice that doesn't work with the latest components.

**Comment by dev-tom-0108** [comment]
It's a node version issue. Please install 14.17.0

**Comment by dev-tom-0108** [comment]
It's a node version issue. Please install 14.17.0

**Comment by dev-tom-0108** [comment]
It's a node version issue. Please install 14.17.0

**Comment by waugh** [comment]
@dev-tom-0108, is it true or not true that 17.0.1 >= 14.0.0?

**Comment by harish-sethuraman** [comment]
I used the exact same Node version (`17.0.1`) to repro but it works fine for me. 
Device: MacBook Pro (16-inch, 2019)
