### ISSUE TITLE
I caught an issue while creating react-app with the below command

### ISSUE THREAD

**Issue by vanishree165** [reactjs/reactjs.org#4771]
C:\Users\vanishree.r>npx create-react-app sample-react-app
npx: installed 67 in 24.301s

Creating a new React app in C:\Users\vanishree.r\sample-react-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

Aborting installation.
Unexpected error. Please report it as a bug:
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:667:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:871:17)
    at spawn (C:\Users\vanishree.r\AppData\Roaming\npm-cache\_npx\1628\node_modules\create-react-app\node_modules\cross-spawn\index.js:12:24)
    at C:\Users\vanishree.r\AppData\Roaming\npm-cache\_npx\1628\node_modules\create-react-app\createReactApp.js:383:19
    at new Promise (<anonymous>)
    at install (C:\Users\vanishree.r\AppData\Roaming\npm-cache\_npx\1628\node_modules\create-react-app\createReactApp.js:334:10)
    at C:\Users\vanishree.r\AppData\Roaming\npm-cache\_npx\1628\node_modules\create-react-app\createReactApp.js:461:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Deleting generated file... package.json
Deleting sample-react-app/ from C:\Users\vanishree.r
Done.

**Comment by gaearon** [comment]
Please file an issue in https://github.com/facebook/create-react-app instead.

That said this looks like calling `npm` fails on your system. Try again or try reinstalling Node.
